### ISSUE TITLE
Occasionally hiccups on latest

### ISSUE THREAD

**Issue by TurtIeSocks** [versx/NodeTileserverCache#8]
```
tileserver-cache | [17:47:21] [error] Stderr: convert: improper image header `/app/Cache/Static/osm-bright-28.586773297747506--81.43412192397706-16-375-300-1.png' @ error/png.c/ReadPNGImage/4294.

tileserver-cache | convert: image sequence is required `-composite' @ error/mogrify.c/MogrifyImageList/7987.

tileserver-cache | convert: no images defined `/app/Cache/StaticWithMarkers/osm-bright-myLatitude-myLongitude-16-375-300-aed8ef2410fd0ec10606b01d3d32a701-1.png' @ error/convert.c/ConvertImageCommand/3273.

tileserver-cache |

tileserver-cache | [17:47:21] [info] Serving Static: /app/Cache/StaticWithMarkers/osm-bright-myLatitude-myLongitude-16-375-300-aed8ef2410fd0ec10606b01d3d32a701-1.png

tileserver-cache | [17:47:21] [error] Failed to send static file: {"errno":-2,"code":"ENOENT","syscall":"stat","path":"/app/Cache/StaticWithMarkers/osm-bright-myLatitude-myLongitude-16-375-300-aed8ef2410fd0ec10606b01d3d32a701-1.png","expose":false,"statusCode":404,"status":404}

tileserver-cache | [17:47:21] [error] Child process exited with non zero exit code: 1
```

myLatitude & myLongitude are replacements for the actual coordinates.

**Comment by versx** [comment]
Should hopefully be fixed in the `circles` branch.

**Comment by TurtIeSocks** [comment]
Circles branch has been merged into master, right? Still seeing this pop up a bit. Seems to be overall more consistent though with the latest pr. Love the addition of circles :)
